/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 4:47:06 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <com.vanna.KhmerKeyboard.Keyboard/com.vanna.KhmerKeyboard.Keyboard-Structs.h>
#import <UIKit/UIButton.h>

@class NSString;

@interface com_vanna_KhmerKeyboard_Keyboard.SuggestionButton : UIButton {

	 count;
	 title;

}

@property (assign,nonatomic) long long count; 
@property (copy,nonatomic) NSString * title; 
-(id)initWithFrame:(CGRect)arg1 title:(id)arg2 count:(long long)arg3 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(long long)count;
-(void)setTitle:(NSString *)arg1 ;
-(NSString *)title;
-(void)setCount:(long long)arg1 ;
-(void)buttonPressed;
@end

