/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 4:47:06 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class _TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase, NSString;

@interface com_vanna_KhmerKeyboard_Keyboard.UserUnigramSaveOperation : NSOperation {

	 db;
	 unigram;
	 status;

}

@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase * db; 
@property (copy,nonatomic) NSString * unigram; 
-(NSString *)unigram;
-(void)setUnigram:(NSString *)arg1 ;
-(id)initWithUnigram:(id)arg1 db:(id)arg2 ;
-(id)init;
-(void)main;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase *)db;
-(void)setDb:(_TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase *)arg1 ;
@end

