/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 4:47:06 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <com.vanna.KhmerKeyboard.Keyboard/com.vanna.KhmerKeyboard.Keyboard-Structs.h>
#import <UIKit/UIView.h>

@class NSArray, UIButton;

@interface com_vanna_KhmerKeyboard_Keyboard.ThemeChooser : UIView {

	 themes;
	 whiteButton;
	 blackButton;
	 event;

}

@property (copy,nonatomic) NSArray * themes; 
@property (retain,nonatomic) UIButton * whiteButton; 
@property (retain,nonatomic) UIButton * blackButton; 
-(UIButton *)whiteButton;
-(void)setWhiteButton:(UIButton *)arg1 ;
-(UIButton *)blackButton;
-(void)setBlackButton:(UIButton *)arg1 ;
-(void)addButtons;
-(void)buttonTouchedDown:(id)arg1 ;
-(void)animateToSmall:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(NSArray *)themes;
-(void)setThemes:(NSArray *)arg1 ;
@end

