/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 4:47:06 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class _TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase, NSDictionary;

@interface com_vanna_KhmerKeyboard_Keyboard.SaveDataToDatabaseOperation : NSOperation {

	 analyticDB;
	 database;
	 data;

}

@property (readonly,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase * database; 
@property (copy,nonatomic) NSDictionary * data; 
-(id)init;
-(NSDictionary *)data;
-(void)setData:(NSDictionary *)arg1 ;
-(id)initWithData:(id)arg1 ;
-(void)main;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase *)database;
@end

