/*
* This header is generated by classdump-dyld 1.0
* on Thursday, August 25, 2016 at 4:47:06 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <com.vanna.KhmerKeyboard.Keyboard/com.vanna.KhmerKeyboard.Keyboard-Structs.h>
@class NSString;

@interface SSZipArchive : NSObject {

	NSString* _path;
	NSString* _filename;
	void* _zip;
	BOOL _open;
	BOOL _close;

}

@property (getter=isOpen,nonatomic,readonly) BOOL open;                 //@synthesize open=_open - In the implementation block
@property (getter=isClosed,nonatomic,readonly) BOOL close;              //@synthesize close=_close - In the implementation block
+(BOOL)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 delegate:(id)arg3 ;
+(BOOL)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(BOOL)arg3 password:(id)arg4 error:(id*)arg5 delegate:(id)arg6 progressHandler:(/*^block*/id)arg7 completionHandler:(/*^block*/id)arg8 ;
+(id)_dateWithMSDOSFormat:(unsigned)arg1 ;
+(BOOL)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(BOOL)arg3 password:(id)arg4 error:(id*)arg5 delegate:(id)arg6 ;
+(BOOL)createZipFileAtPath:(id)arg1 withFilesAtPaths:(id)arg2 withPassword:(id)arg3 ;
+(BOOL)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2 withPassword:(id)arg3 ;
+(BOOL)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2 keepParentDirectory:(BOOL)arg3 withPassword:(id)arg4 ;
+(BOOL)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 ;
+(BOOL)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(BOOL)arg3 password:(id)arg4 error:(id*)arg5 ;
+(BOOL)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 overwrite:(BOOL)arg3 password:(id)arg4 progressHandler:(/*^block*/id)arg5 completionHandler:(/*^block*/id)arg6 ;
+(BOOL)unzipFileAtPath:(id)arg1 toDestination:(id)arg2 progressHandler:(/*^block*/id)arg3 completionHandler:(/*^block*/id)arg4 ;
+(BOOL)createZipFileAtPath:(id)arg1 withFilesAtPaths:(id)arg2 ;
+(BOOL)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2 ;
+(BOOL)createZipFileAtPath:(id)arg1 withContentsOfDirectory:(id)arg2 keepParentDirectory:(BOOL)arg3 ;
-(BOOL)writeFile:(id)arg1 withPassword:(id)arg2 ;
-(BOOL)writeFileAtPath:(id)arg1 withFileName:(id)arg2 withPassword:(id)arg3 ;
-(void)zipInfo:(SCD_Struct_SS0*)arg1 setDate:(id)arg2 ;
-(BOOL)writeFolderAtPath:(id)arg1 withFolderName:(id)arg2 withPassword:(id)arg3 ;
-(BOOL)writeData:(id)arg1 filename:(id)arg2 withPassword:(id)arg3 ;
-(BOOL)close;
-(id)initWithPath:(id)arg1 ;
-(BOOL)open;
-(BOOL)isClosed;
-(BOOL)isOpen;
@end

