/*
* This header is generated by classdump-dyld 1.0
* on Monday, September 5, 2016 at 8:26:25 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <KhmerKeyboard/FBSDKAccessTokenCaching.h>

@class NSString;

@interface FBSDKAccessTokenCacheV3 : NSObject <FBSDKAccessTokenCaching>

@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
+(id)accessTokenForV3Dictionary:(id)arg1 ;
-(id)fetchAccessToken;
-(void)cacheAccessToken:(id)arg1 ;
-(void)clearCache;
@end

