/*
* This header is generated by classdump-dyld 1.0
* on Monday, September 5, 2016 at 8:26:25 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKBase64 : NSObject {

	BOOL _optionsEnabled;

}
+(id)decodeAsData:(id)arg1 ;
+(id)decodeAsString:(id)arg1 ;
+(id)encodeString:(id)arg1 ;
+(void)initialize;
+(id)encodeData:(id)arg1 ;
-(id)decodeAsData:(id)arg1 ;
-(id)initWithOptionsEnabled:(BOOL)arg1 ;
-(id)decodeAsString:(id)arg1 ;
-(id)encodeString:(id)arg1 ;
-(id)init;
-(id)encodeData:(id)arg1 ;
@end

