/*
* This header is generated by classdump-dyld 1.0
* on Monday, September 5, 2016 at 8:26:25 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class UIImageView, NSString;

@interface KhmerKeyboard.PageContentViewController : UIViewController {

	 imageView;
	 imageName;
	 pageIndex;

}

@property (assign,__weak,nonatomic) UIImageView * imageView; 
@property (copy,nonatomic) NSString * imageName; 
-(id)initWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
-(UIImageView *)imageView;
-(void)setImageView:(UIImageView *)arg1 ;
-(void)setImageName:(NSString *)arg1 ;
-(NSString *)imageName;
@end

