/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class _TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase, NSString;

@interface com_vanna_KhmerKeyboard_Keyboard.UserTrigramSaveOperation : NSOperation {

	 db;
	 term1;
	 term2;
	 term3;
	 status;

}

@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase * db; 
@property (copy,nonatomic) NSString * term1; 
@property (copy,nonatomic) NSString * term2; 
@property (copy,nonatomic) NSString * term3; 
-(NSString *)term1;
-(void)setTerm1:(NSString *)arg1 ;
-(NSString *)term2;
-(void)setTerm2:(NSString *)arg1 ;
-(NSString *)term3;
-(void)setTerm3:(NSString *)arg1 ;
-(id)initWithTerm1:(id)arg1 term2:(id)arg2 term3:(id)arg3 db:(id)arg4 ;
-(id)init;
-(void)main;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase *)db;
-(void)setDb:(_TtC32com_vanna_KhmerKeyboard_Keyboard14SQLiteDatabase *)arg1 ;
@end

