/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <libobjc.A.dylib/NSCoding.h>

@class NSURL, NSString, NSData;

@interface com_vanna_KhmerKeyboard_Keyboard.Upload : NSObject <NSCoding> {

	 fileUrl;
	 mimeType;
	 data;
	 fileName;

}

@property (retain,nonatomic) NSURL * fileUrl; 
@property (copy,nonatomic) NSString * mimeType; 
@property (retain,nonatomic) NSData * data; 
@property (copy,nonatomic) NSString * fileName; 
-(NSURL *)fileUrl;
-(void)setFileUrl:(NSURL *)arg1 ;
-(void)getMimeType;
-(id)getDataAndReturnError:(id*)arg1 ;
-(id)initWithFileUrl:(id)arg1 ;
-(id)initWithData:(id)arg1 fileName:(id)arg2 mimeType:(id)arg3 ;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(NSData *)data;
-(void)setData:(NSData *)arg1 ;
-(NSString *)mimeType;
-(void)setMimeType:(NSString *)arg1 ;
-(NSString *)fileName;
-(void)setFileName:(NSString *)arg1 ;
@end

