/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class _TtC32com_vanna_KhmerKeyboard_Keyboard29EmojiCollectionViewController, UIView, NSArray, NSTimer, UIButton;

@interface com_vanna_KhmerKeyboard_Keyboard.EmojiKeyboardViewController : UIViewController {

	 space;
	 x;
	 lastY;
	 ICON_FONT_SIZE;
	 keyWidth;
	 keyHeight;
	 buttonClickEvent;
	 emojiCollectionViewController;
	 keyboardDelegate;
	 bottomButtonBox;
	 viewContainer;
	 emojiCategoryButtons;
	 deleteButtonTimer;
	 swicthButton;
	 recentButton;
	 button;
	 deleteButton;
	 themeManager;
	 theme;

}

@property (assign,nonatomic) double space; 
@property (assign,nonatomic) double x; 
@property (assign,nonatomic) double lastY; 
@property (readonly,nonatomic) double ICON_FONT_SIZE; 
@property (assign,nonatomic) double keyWidth; 
@property (assign,nonatomic) double keyHeight; 
@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard29EmojiCollectionViewController * emojiCollectionViewController; 
@property (assign,__weak,nonatomic) UIView * bottomButtonBox; 
@property (assign,__weak,nonatomic) UIView * viewContainer; 
@property (copy,nonatomic) NSArray * emojiCategoryButtons; 
@property (retain,nonatomic) NSTimer * deleteButtonTimer; 
@property (retain,nonatomic) UIButton * swicthButton; 
@property (retain,nonatomic) UIButton * recentButton; 
@property (retain,nonatomic) UIButton * button; 
@property (retain,nonatomic) UIButton * deleteButton; 
-(void)applyThemeColor:(id)arg1 foregroundColor:(id)arg2 ;
-(double)lastY;
-(void)setLastY:(double)arg1 ;
-(double)ICON_FONT_SIZE;
-(double)keyWidth;
-(void)setKeyWidth:(double)arg1 ;
-(double)keyHeight;
-(void)setKeyHeight:(double)arg1 ;
-(void)setEmojiCollectionViewController:(_TtC32com_vanna_KhmerKeyboard_Keyboard29EmojiCollectionViewController *)arg1 ;
-(void)setBottomButtonBox:(UIView *)arg1 ;
-(UIView *)viewContainer;
-(void)setViewContainer:(UIView *)arg1 ;
-(NSArray *)emojiCategoryButtons;
-(void)setEmojiCategoryButtons:(NSArray *)arg1 ;
-(NSTimer *)deleteButtonTimer;
-(void)setDeleteButtonTimer:(NSTimer *)arg1 ;
-(UIButton *)swicthButton;
-(void)setSwicthButton:(UIButton *)arg1 ;
-(UIButton *)recentButton;
-(void)setRecentButton:(UIButton *)arg1 ;
-(void)onSizeChanged;
-(void)applyTheme;
-(void)abcButtonClicked;
-(void)deleteButtonPressed:(id)arg1 ;
-(void)handleLongPressForDeleteButtonWithGestureRecognizer:(id)arg1 ;
-(void)handleSwipeLeftForDeleteButtonWithGestureRecognizer:(id)arg1 ;
-(void)handleDeleteButtonTimerTick:(id)arg1 ;
-(void)resetEmojiCategoryButtons;
-(void)highLightSectionButton:(long long)arg1 ;
-(void)emojiButtonClicked:(id)arg1 ;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard29EmojiCollectionViewController *)emojiCollectionViewController;
-(UIView *)bottomButtonBox;
-(UIButton *)button;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)initialize;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(void)prepareForSegue:(id)arg1 sender:(id)arg2 ;
-(double)x;
-(void)setX:(double)arg1 ;
-(void)setButton:(UIButton *)arg1 ;
-(UIButton *)deleteButton;
-(void)setDeleteButton:(UIButton *)arg1 ;
-(void)setSpace:(double)arg1 ;
-(double)space;
@end

