/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIAlertViewDelegate.h>

@protocol FBSDKGraphErrorRecoveryProcessorDelegate;
@class FBSDKErrorRecoveryAttempter, NSError, UIAlertView, NSString;

@interface FBSDKGraphErrorRecoveryProcessor : NSObject <UIAlertViewDelegate> {

	FBSDKErrorRecoveryAttempter* _recoveryAttempter;
	NSError* _error;
	UIAlertView* _alertView;
	id<FBSDKGraphErrorRecoveryProcessorDelegate> _delegate;

}

@property (nonatomic,retain) id<FBSDKGraphErrorRecoveryProcessorDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (readonly) unsigned long long hash; 
@property (readonly) Class superclass; 
@property (copy,readonly) NSString * description; 
@property (copy,readonly) NSString * debugDescription; 
-(void)displayAlertWithRecoverySuggestion:(id)arg1 recoveryOptionsTitles:(id)arg2 ;
-(void)displayAlertWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3 ;
-(void)didPresentErrorWithRecovery:(BOOL)arg1 contextInfo:(void*)arg2 ;
-(BOOL)processError:(id)arg1 request:(id)arg2 delegate:(id)arg3 ;
-(void)setDelegate:(id<FBSDKGraphErrorRecoveryProcessorDelegate>)arg1 ;
-(void)dealloc;
-(id<FBSDKGraphErrorRecoveryProcessorDelegate>)delegate;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2 ;
@end

