/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <com.vanna.KhmerKeyboard.Keyboard/com.vanna.KhmerKeyboard.Keyboard-Structs.h>
@interface FBSDKMath : NSObject
+(unsigned long long)hashWithIntegerArray:(unsigned long long*)arg1 count:(unsigned long long)arg2 ;
+(unsigned long long)hashWithDouble:(double)arg1 ;
+(unsigned long long)hashWithLong:(unsigned long long)arg1 ;
+(unsigned long long)hashWithInteger:(unsigned long long)arg1 ;
+(unsigned long long)hashWithPointer:(const void*)arg1 ;
+(unsigned long long)hashWithInteger:(unsigned long long)arg1 andInteger:(unsigned long long)arg2 ;
+(CGPoint)ceilForPoint:(CGPoint)arg1 ;
+(CGSize)ceilForSize:(CGSize)arg1 ;
+(CGPoint)floorForPoint:(CGPoint)arg1 ;
+(CGSize)floorForSize:(CGSize)arg1 ;
+(unsigned long long)hashWithCGFloat:(double)arg1 ;
+(unsigned long long)hashWithCString:(const char*)arg1 ;
+(unsigned long long)hashWithFloat:(float)arg1 ;
-(id)init;
@end

