/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKTypeUtility : NSObject
+(id)dictionaryValue:(id)arg1 ;
+(unsigned long long)unsignedIntegerValue:(id)arg1 ;
+(id)stringValue:(id)arg1 ;
+(BOOL)boolValue:(id)arg1 ;
+(double)timeIntervalValue:(id)arg1 ;
+(id)arrayValue:(id)arg1 ;
+(id)URLValue:(id)arg1 ;
+(id)_objectValue:(id)arg1 ofClass:(Class)arg2 ;
+(id)objectValue:(id)arg1 ;
+(long long)integerValue:(id)arg1 ;
-(id)init;
@end

