/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKSettings : NSObject
+(BOOL)isGraphErrorRecoveryDisabled;
+(id)graphAPIDebugParamValue;
+(void)setGraphErrorRecoveryDisabled:(BOOL)arg1 ;
+(double)JPEGCompressionQuality;
+(id)loggingBehavior;
+(id)accessTokenCache;
+(id)appURLSchemeSuffix;
+(id)facebookDomainPart;
+(id)legacyUserDefaultTokenInformationKeyName;
+(BOOL)limitEventAndDataUsage;
+(id)_JPEGCompressionQualityNumber;
+(void)_setJPEGCompressionQualityNumber:(id)arg1 ;
+(void)updateGraphAPIDebugBehavior;
+(void)setAppURLSchemeSuffix:(id)arg1 ;
+(void)setClientToken:(id)arg1 ;
+(void)setFacebookDomainPart:(id)arg1 ;
+(void)setJPEGCompressionQuality:(double)arg1 ;
+(void)setLimitEventAndDataUsage:(BOOL)arg1 ;
+(void)setLoggingBehavior:(id)arg1 ;
+(void)enableLoggingBehavior:(id)arg1 ;
+(void)disableLoggingBehavior:(id)arg1 ;
+(void)setLegacyUserDefaultTokenInformationKeyName:(id)arg1 ;
+(id)userAgentSuffix;
+(void)setUserAgentSuffix:(id)arg1 ;
+(void)initialize;
+(id)displayName;
+(void)setDisplayName:(id)arg1 ;
+(void)setAppID:(id)arg1 ;
+(id)clientToken;
+(id)sdkVersion;
+(id)appID;
-(void)setAccessTokenCache:(id)arg1 ;
-(id)init;
@end

