/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:16:33 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <com.vanna.KhmerKeyboard.Keyboard/com.vanna.KhmerKeyboard.Keyboard-Structs.h>
@interface FBSDKInternalUtility : NSObject
+(void)extractPermissionsFromResponse:(id)arg1 grantedPermissions:(id)arg2 declinedPermissions:(id)arg3 ;
+(void)array:(id)arg1 addObject:(id)arg2 ;
+(BOOL)isOSRunTimeVersionAtLeast:(SCD_Struct_FB3)arg1 ;
+(id)queryStringWithDictionary:(id)arg1 error:(id*)arg2 invalidObjectHandler:(/*^block*/id)arg3 ;
+(id)JSONStringForObject:(id)arg1 error:(id*)arg2 invalidObjectHandler:(/*^block*/id)arg3 ;
+(unsigned long long)currentTimeInMilliseconds;
+(void)dictionary:(id)arg1 setObject:(id)arg2 forKey:(id)arg3 ;
+(void)deleteFacebookCookies;
+(BOOL)object:(id)arg1 isEqualToObject:(id)arg2 ;
+(id)URLWithScheme:(id)arg1 host:(id)arg2 path:(id)arg3 queryParameters:(id)arg4 error:(id*)arg5 ;
+(id)facebookURLWithHostPrefix:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 defaultVersion:(id)arg4 error:(id*)arg5 ;
+(long long)_compareOperatingSystemVersion:(SCD_Struct_FB3)arg1 toVersion:(SCD_Struct_FB3)arg2 ;
+(id)_convertObjectToJSONObject:(id)arg1 invalidObjectHandler:(/*^block*/id)arg2 stop:(BOOL*)arg3 ;
+(BOOL)isUIKitLinkTimeVersionAtLeast:(int)arg1 ;
+(id)convertRequestValue:(id)arg1 ;
+(BOOL)isUIKitRunTimeVersionAtLeast:(int)arg1 ;
+(id)facebookURLWithHostPrefix:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 error:(id*)arg4 ;
+(void)checkRegisteredCanOpenURLScheme:(id)arg1 ;
+(void)validateAppID;
+(BOOL)isRegisteredURLScheme:(id)arg1 ;
+(BOOL)isRegisteredCanOpenURLScheme:(id)arg1 ;
+(BOOL)isPublishPermission:(id)arg1 ;
+(id)appURLWithHost:(id)arg1 path:(id)arg2 queryParameters:(id)arg3 error:(id*)arg4 ;
+(id)dictionaryFromFBURL:(id)arg1 ;
+(id)bundleForStrings;
+(BOOL)dictionary:(id)arg1 setJSONStringForObject:(id)arg2 forKey:(id)arg3 error:(id*)arg4 ;
+(BOOL)isBrowserURL:(id)arg1 ;
+(BOOL)isFacebookBundleIdentifier:(id)arg1 ;
+(BOOL)isSafariBundleIdentifier:(id)arg1 ;
+(id)objectForJSONString:(id)arg1 error:(id*)arg2 ;
+(BOOL)shouldManuallyAdjustOrientation;
+(void)registerTransientObject:(id)arg1 ;
+(void)unregisterTransientObject:(id)arg1 ;
+(BOOL)isFacebookAppInstalled;
+(BOOL)isMessengerAppInstalled;
+(id)validateRequiredClientAccessToken;
+(void)validateURLSchemes;
+(void)validateFacebookReservedURLSchemes;
+(id)topMostViewController;
+(id)hexadecimalStringFromData:(id)arg1 ;
+(BOOL)areAllPermissionsReadPermissions:(id)arg1 ;
+(BOOL)areAllPermissionsPublishPermissions:(id)arg1 ;
+(Class)resolveBoltsClassWithName:(id)arg1 ;
+(SCD_Struct_FB3)operatingSystemVersion;
+(id)viewControllerForView:(id)arg1 ;
+(id)appURLScheme;
-(id)init;
@end

