/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:24:09 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <KhmerKeyboard/KhmerKeyboard-Structs.h>
#import <libobjc.A.dylib/NSCopying.h>
#import <libobjc.A.dylib/NSSecureCoding.h>

@class NSString, NSURL, NSDate;

@interface FBSDKProfile : NSObject <NSCopying, NSSecureCoding> {

	NSString* _userID;
	NSString* _firstName;
	NSString* _middleName;
	NSString* _lastName;
	NSString* _name;
	NSURL* _linkURL;
	NSDate* _refreshDate;

}

@property (nonatomic,readonly) NSString * userID;                  //@synthesize userID=_userID - In the implementation block
@property (nonatomic,readonly) NSString * firstName;               //@synthesize firstName=_firstName - In the implementation block
@property (nonatomic,readonly) NSString * middleName;              //@synthesize middleName=_middleName - In the implementation block
@property (nonatomic,readonly) NSString * lastName;                //@synthesize lastName=_lastName - In the implementation block
@property (nonatomic,readonly) NSString * name;                    //@synthesize name=_name - In the implementation block
@property (nonatomic,readonly) NSURL * linkURL;                    //@synthesize linkURL=_linkURL - In the implementation block
@property (nonatomic,readonly) NSDate * refreshDate;               //@synthesize refreshDate=_refreshDate - In the implementation block
+(id)fetchCachedProfile;
+(void)cacheProfile:(id)arg1 ;
+(void)setCurrentProfile:(id)arg1 ;
+(void)observeChangeAccessTokenChange:(id)arg1 ;
+(void)loadProfileWithToken:(id)arg1 completion:(/*^block*/id)arg2 ;
+(id)currentProfile;
+(void)enableUpdatesOnAccessTokenChange:(BOOL)arg1 ;
+(void)loadCurrentProfileWithCompletion:(/*^block*/id)arg1 ;
+(BOOL)supportsSecureCoding;
-(NSDate *)refreshDate;
-(BOOL)isEqualToProfile:(id)arg1 ;
-(id)imagePathForPictureMode:(unsigned long long)arg1 size:(CGSize)arg2 ;
-(id)initWithUserID:(id)arg1 firstName:(id)arg2 middleName:(id)arg3 lastName:(id)arg4 name:(id)arg5 linkURL:(id)arg6 refreshDate:(id)arg7 ;
-(id)imageURLForPictureMode:(unsigned long long)arg1 size:(CGSize)arg2 ;
-(NSString *)middleName;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(id)init;
-(BOOL)isEqual:(id)arg1 ;
-(unsigned long long)hash;
-(NSString *)name;
-(id)copyWithZone:(NSZone*)arg1 ;
-(NSURL *)linkURL;
-(NSString *)firstName;
-(NSString *)lastName;
-(NSString *)userID;
@end

