/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:24:09 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class UIButton, UILabel;

@interface KhmerKeyboard.ELViewController : UIViewController {

	 setupButton;
	 setupLabel;
	 usageLabel;
	 lblstartup;
	 settinglabel;
	 settingbutton;
	 textHowtoinstall;
	 textHowtouse;

}

@property (assign,__weak,nonatomic) UIButton * setupButton; 
@property (assign,__weak,nonatomic) UILabel * setupLabel; 
@property (assign,__weak,nonatomic) UILabel * usageLabel; 
@property (assign,__weak,nonatomic) UILabel * lblstartup; 
@property (assign,__weak,nonatomic) UILabel * settinglabel; 
@property (assign,__weak,nonatomic) UIButton * settingbutton; 
@property (assign,__weak,nonatomic) UIButton * textHowtoinstall; 
@property (assign,__weak,nonatomic) UIButton * textHowtouse; 
-(UIButton *)setupButton;
-(void)setSetupButton:(UIButton *)arg1 ;
-(UILabel *)setupLabel;
-(void)setSetupLabel:(UILabel *)arg1 ;
-(UILabel *)usageLabel;
-(void)setUsageLabel:(UILabel *)arg1 ;
-(UILabel *)lblstartup;
-(void)setLblstartup:(UILabel *)arg1 ;
-(void)buttonDonation:(id)arg1 ;
-(void)setupButtonPressed:(id)arg1 ;
-(void)setSettinglabel:(UILabel *)arg1 ;
-(void)setSettingbutton:(UIButton *)arg1 ;
-(UIButton *)textHowtoinstall;
-(void)setTextHowtoinstall:(UIButton *)arg1 ;
-(UIButton *)textHowtouse;
-(void)setTextHowtouse:(UIButton *)arg1 ;
-(UILabel *)settinglabel;
-(UIButton *)settingbutton;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)handlePan:(id)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)prepareForSegue:(id)arg1 sender:(id)arg2 ;
@end

