/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:24:09 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class NSUserDefaults, UISwitch;

@interface KhmerKeyboard.SettingViewController : UIViewController {

	 mySharedDefaults;
	 onbutton;
	 zeroSpaceSwitcha;

}

@property (retain,nonatomic) NSUserDefaults * mySharedDefaults; 
@property (assign,__weak,nonatomic) UISwitch * onbutton; 
@property (assign,__weak,nonatomic) UISwitch * zeroSpaceSwitcha; 
-(void)animateView:(id)arg1 withAlpha:(double)arg2 duration:(double)arg3 ;
-(void)spaceCursorStateChanged:(id)arg1 ;
-(void)zeroSpaceStateChanged:(id)arg1 ;
-(void)themeButtonPressed:(id)arg1 ;
-(void)charThemeButtonPressed:(id)arg1 ;
-(void)photoPickerButtonPressed:(id)arg1 ;
-(void)imagePickerControllerDidCancel:(id)arg1 ;
-(void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2 ;
-(void)themeOptionChanged:(id)arg1 ;
-(void)viewDidLayoutSubviews;
-(void)setMySharedDefaults:(NSUserDefaults *)arg1 ;
-(UISwitch *)onbutton;
-(void)setOnbutton:(UISwitch *)arg1 ;
-(void)dismissButtonPressed:(id)arg1 ;
-(void)setSpacebutton:(id)arg1 ;
-(void)setZeroSpaceSwitcha:(UISwitch *)arg1 ;
-(UISwitch *)zeroSpaceSwitcha;
-(NSUserDefaults *)mySharedDefaults;
-(id)initWithCoder:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
@end

