/*
* This header is generated by classdump-dyld 1.0
* on Thursday, September 15, 2016 at 5:24:09 PM Central European Summer Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/9A6F22DF-17D7-49A9-A081-D16D43AD007A/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class UILabel;

@interface KhmerKeyboard.InfoViewController : UIViewController {

	 lblversion;

}

@property (assign,__weak,nonatomic) UILabel * lblversion; 
-(UILabel *)lblversion;
-(void)setLblversion:(UILabel *)arg1 ;
-(void)dimissButtonPressed:(id)arg1 ;
-(void)aliendevButtonPressed:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
@end

