/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 31, 2016 at 11:31:58 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKTypeUtility : NSObject
+(id)dictionaryValue:(id)arg1 ;
+(unsigned long long)unsignedIntegerValue:(id)arg1 ;
+(id)stringValue:(id)arg1 ;
+(BOOL)boolValue:(id)arg1 ;
+(double)timeIntervalValue:(id)arg1 ;
+(id)arrayValue:(id)arg1 ;
+(id)URLValue:(id)arg1 ;
+(id)_objectValue:(id)arg1 ofClass:(Class)arg2 ;
+(id)objectValue:(id)arg1 ;
+(long long)integerValue:(id)arg1 ;
-(id)init;
@end

