/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 31, 2016 at 11:31:58 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKUtility : NSObject
+(id)dictionaryWithQueryString:(id)arg1 ;
+(id)URLDecode:(id)arg1 ;
+(id)queryStringWithDictionary:(id)arg1 error:(id*)arg2 ;
+(id)URLEncode:(id)arg1 ;
-(id)init;
@end

