/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 31, 2016 at 11:31:58 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <KhmerKeyboard/KhmerKeyboard-Structs.h>
@interface FBSDKDynamicFrameworkLoader : NSObject
+(SecRandomRef)loadkSecRandomDefault;
+(void*)loadkSecAttrAccessible;
+(void*)loadkSecAttrAccessibleAfterFirstUnlockThisDeviceOnly;
+(void*)loadkSecAttrAccount;
+(void*)loadkSecAttrService;
+(void*)loadkSecAttrGeneric;
+(void*)loadkSecValueData;
+(void*)loadkSecClassGenericPassword;
+(void*)loadkSecAttrAccessGroup;
+(void*)loadkSecMatchLimitOne;
+(void*)loadkSecMatchLimit;
+(void*)loadkSecReturnData;
+(void*)loadkSecClass;
-(id)init;
@end

