/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 31, 2016 at 11:31:58 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <KhmerKeyboard/KhmerKeyboard-Structs.h>
@interface FBSDKMath : NSObject
+(unsigned long long)hashWithIntegerArray:(unsigned long long*)arg1 count:(unsigned long long)arg2 ;
+(unsigned long long)hashWithDouble:(double)arg1 ;
+(unsigned long long)hashWithLong:(unsigned long long)arg1 ;
+(unsigned long long)hashWithInteger:(unsigned long long)arg1 ;
+(unsigned long long)hashWithPointer:(const void*)arg1 ;
+(unsigned long long)hashWithInteger:(unsigned long long)arg1 andInteger:(unsigned long long)arg2 ;
+(CGPoint)ceilForPoint:(CGPoint)arg1 ;
+(CGSize)ceilForSize:(CGSize)arg1 ;
+(CGPoint)floorForPoint:(CGPoint)arg1 ;
+(CGSize)floorForSize:(CGSize)arg1 ;
+(unsigned long long)hashWithCGFloat:(double)arg1 ;
+(unsigned long long)hashWithCString:(const char*)arg1 ;
+(unsigned long long)hashWithFloat:(float)arg1 ;
-(id)init;
@end

