/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 31, 2016 at 11:31:58 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>

@class NSUserDefaults, UISwitch;

@interface KhmerKeyboard.SettingViewController : UIViewController {

	 mySharedDefaults;
	 onbutton;
	 zeroSpaceSwitcha;

}

@property (retain,nonatomic) NSUserDefaults * mySharedDefaults; 
@property (assign,__weak,nonatomic) UISwitch * onbutton; 
@property (assign,__weak,nonatomic) UISwitch * zeroSpaceSwitcha; 
-(NSUserDefaults *)mySharedDefaults;
-(void)setMySharedDefaults:(NSUserDefaults *)arg1 ;
-(UISwitch *)onbutton;
-(void)setOnbutton:(UISwitch *)arg1 ;
-(UISwitch *)zeroSpaceSwitcha;
-(void)setZeroSpaceSwitcha:(UISwitch *)arg1 ;
-(void)dismissButtonPressed:(id)arg1 ;
-(void)setSpacebutton:(id)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)viewDidLoad;
@end

