/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 31, 2016 at 11:31:58 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <UIKit/UIPageViewControllerDataSource.h>

@class UIView, NSArray;

@interface KhmerKeyboard.InstructionPageViewController : UIViewController <UIPageViewControllerDataSource> {

	 ContainerView;
	 images;
	 pageDescription;

}

@property (assign,__weak,nonatomic) UIView * ContainerView; 
@property (copy,nonatomic) NSArray * images; 
@property (copy,nonatomic) NSArray * pageDescription; 
-(id)viewControllerAtIndex:(long long)arg1 ;
-(UIView *)ContainerView;
-(NSArray *)pageDescription;
-(void)setPageDescription:(NSArray *)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(NSArray *)images;
-(void)setContainerView:(UIView *)arg1 ;
-(void)viewDidLoad;
-(void)setImages:(NSArray *)arg1 ;
-(id)pageViewController:(id)arg1 viewControllerBeforeViewController:(id)arg2 ;
-(id)pageViewController:(id)arg1 viewControllerAfterViewController:(id)arg2 ;
-(long long)presentationCountForPageViewController:(id)arg1 ;
-(long long)presentationIndexForPageViewController:(id)arg1 ;
@end

