/*
* This header is generated by classdump-dyld 1.0
* on Wednesday, August 31, 2016 at 11:31:58 AM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /var/containers/Bundle/Application/A4832F78-521A-4050-AC12-690EABD61C51/KhmerKeyboard.app/KhmerKeyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@protocol UIAlertViewDelegate <NSObject>
@optional
-(void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
-(void)alertViewCancel:(id)arg1;
-(void)willPresentAlertView:(id)arg1;
-(void)didPresentAlertView:(id)arg1;
-(void)alertView:(id)arg1 willDismissWithButtonIndex:(long long)arg2;
-(void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
-(BOOL)alertViewShouldEnableFirstOtherButton:(id)arg1;

@end

