/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 4, 2016 at 9:15:10 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <com.vanna.KhmerKeyboard.Keyboard/com.vanna.KhmerKeyboard.Keyboard-Structs.h>
#import <UIKit/UIView.h>

@class NSArray, _TtC32com_vanna_KhmerKeyboard_Keyboard12ThemeChooser, UIScrollView;

@interface com_vanna_KhmerKeyboard_Keyboard.GlobePopupView : UIView {

	 languages;
	 userRequestedEvent;
	 themeChooser;
	 scrollView;

}

@property (readonly,nonatomic) NSArray * languages; 
@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard12ThemeChooser * themeChooser; 
@property (retain,nonatomic) UIScrollView * scrollView; 
-(_TtC32com_vanna_KhmerKeyboard_Keyboard12ThemeChooser *)themeChooser;
-(void)setThemeChooser:(_TtC32com_vanna_KhmerKeyboard_Keyboard12ThemeChooser *)arg1 ;
-(void)buttonPressedUp:(id)arg1 ;
-(id)initWithFrame:(CGRect)arg1 ;
-(id)initWithCoder:(id)arg1 ;
-(void)setScrollView:(UIScrollView *)arg1 ;
-(UIScrollView *)scrollView;
-(void)buttonPressed:(id)arg1 ;
-(NSArray *)languages;
@end

