/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 4, 2016 at 9:15:10 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIInputViewController.h>

@class _TtC32com_vanna_KhmerKeyboard_Keyboard27EmojiKeyboardViewController, _TtC32com_vanna_KhmerKeyboard_Keyboard33AdvertisementViewControllerDetail, UIButton, NSLayoutConstraint, _TtC32com_vanna_KhmerKeyboard_Keyboard12KeyboardView, NSUserDefaults, _TtC32com_vanna_KhmerKeyboard_Keyboard15InstructionView, NSString;

@interface com_vanna_KhmerKeyboard_Keyboard.KeyboardViewController : UIInputViewController {

	 currentKeyboardType;
	 containerViewController;
	 AdsViewControllerDetail;
	 spacing;
	 nextKeyboardButton;
	 portraitHeight;
	 highPortraitHeight;
	 landscapeHeight;
	 highLandscapeHeight;
	 portraitHeight_IPAD;
	 highPortraitHeight_IPAD;
	 landscapeHeight_IPAD;
	 highLandscapeHeight_IPAD;
	 heightConstraint;
	 keyboardView;
	 sharedDefaults;
	 isZeroSpace;
	 userDB;
	 instructionView;
	 spacebartheme;
	 charactorbuttonTheme;
	 currentLanguageLabel;
	 keyboardAnalyticOperation;

}

@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard27EmojiKeyboardViewController * containerViewController; 
@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard33AdvertisementViewControllerDetail * AdsViewControllerDetail; 
@property (retain,nonatomic) UIButton * nextKeyboardButton; 
@property (readonly,nonatomic) double portraitHeight; 
@property (readonly,nonatomic) double highPortraitHeight; 
@property (readonly,nonatomic) double landscapeHeight; 
@property (readonly,nonatomic) double highLandscapeHeight; 
@property (readonly,nonatomic) double portraitHeight_IPAD; 
@property (readonly,nonatomic) double highPortraitHeight_IPAD; 
@property (readonly,nonatomic) double landscapeHeight_IPAD; 
@property (readonly,nonatomic) double highLandscapeHeight_IPAD; 
@property (retain,nonatomic) NSLayoutConstraint * heightConstraint; 
@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard12KeyboardView * keyboardView; 
@property (retain,nonatomic) NSUserDefaults * sharedDefaults; 
@property (assign,nonatomic) BOOL isZeroSpace; 
@property (retain,nonatomic) _TtC32com_vanna_KhmerKeyboard_Keyboard15InstructionView * instructionView; 
@property (readonly,nonatomic) NSString * lastWordTyped; 
@property (readonly,nonatomic) NSString * lastWordTypedBeforeDelimiter; 
@property (readonly,nonatomic) NSString * documentContextBeforeInput; 
@property (readonly,nonatomic) NSString * documentContextAfterInput; 
@property (readonly,nonatomic) NSString * lastCharatorTyped; 
-(void)loadEmojiKeyboard;
-(void)loadCharacterKeyboard;
-(void)switchToCharacterKeyboard;
-(void)switchToEmojiKeyboard;
-(void)removeAllSubViews;
-(void)saveToDatabase:(id)arg1 ;
-(void)prepareKeyboaredAnalyticOperations;
-(void)show;
-(void)presentViewController:(id)arg1 animated:(BOOL)arg2 ;
-(void)setAdsViewControllerDetail:(_TtC32com_vanna_KhmerKeyboard_Keyboard33AdvertisementViewControllerDetail *)arg1 ;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard33AdvertisementViewControllerDetail *)AdsViewControllerDetail;
-(UIButton *)nextKeyboardButton;
-(void)setNextKeyboardButton:(UIButton *)arg1 ;
-(double)portraitHeight;
-(double)highPortraitHeight;
-(double)landscapeHeight;
-(double)highLandscapeHeight;
-(double)portraitHeight_IPAD;
-(double)highPortraitHeight_IPAD;
-(double)landscapeHeight_IPAD;
-(double)highLandscapeHeight_IPAD;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard12KeyboardView *)keyboardView;
-(void)setKeyboardView:(_TtC32com_vanna_KhmerKeyboard_Keyboard12KeyboardView *)arg1 ;
-(void)setSharedDefaults:(NSUserDefaults *)arg1 ;
-(BOOL)isZeroSpace;
-(void)setIsZeroSpace:(BOOL)arg1 ;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard15InstructionView *)instructionView;
-(void)setInstructionView:(_TtC32com_vanna_KhmerKeyboard_Keyboard15InstructionView *)arg1 ;
-(NSString *)lastWordTyped;
-(NSString *)lastWordTypedBeforeDelimiter;
-(NSString *)lastCharatorTyped;
-(void)setupEvents;
-(void)requestShortMode;
-(void)requestHighMode;
-(void)setHeightConstraint;
-(void)deleteChunk;
-(void)deleteByTimer;
-(void)nextInputMethod;
-(void)spaceButtonPressed;
-(void)handleSpace;
-(id)getUserPredictionDB;
-(void)hideGlobPopup;
-(void)insertSuggestion:(id)arg1 ;
-(void)toggleEmojiKeyboard;
-(void)showCurrentKeyboard;
-(void)changeKeyboard;
-(void)initializeKeyboard;
-(void)addKeyboardView;
-(void)initInstructionView;
-(void)addHeightContraintHack;
-(void)updateSuggestions;
-(void)changeToPreviousLanguage;
-(void)changeToNextLanguage;
-(id)initWithCoder:(id)arg1 ;
-(void)didReceiveMemoryWarning;
-(id)initWithNibName:(id)arg1 bundle:(id)arg2 ;
-(void)initialize;
-(void)textWillChange:(id)arg1 ;
-(void)insertText:(id)arg1 ;
-(void)viewWillAppear:(BOOL)arg1 ;
-(void)viewDidLoad;
-(void)viewDidAppear:(BOOL)arg1 ;
-(void)viewWillDisappear:(BOOL)arg1 ;
-(void)willRotateToInterfaceOrientation:(long long)arg1 duration:(double)arg2 ;
-(void)didRotateFromInterfaceOrientation:(long long)arg1 ;
-(NSLayoutConstraint *)heightConstraint;
-(void)setHeightConstraint:(NSLayoutConstraint *)arg1 ;
-(NSString *)documentContextBeforeInput;
-(NSString *)documentContextAfterInput;
-(void)delete;
-(void)deleteAll;
-(_TtC32com_vanna_KhmerKeyboard_Keyboard27EmojiKeyboardViewController *)containerViewController;
-(void)setContainerViewController:(_TtC32com_vanna_KhmerKeyboard_Keyboard27EmojiKeyboardViewController *)arg1 ;
-(NSUserDefaults *)sharedDefaults;
-(void)returnPressed;
@end

