/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 4, 2016 at 9:15:10 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <Foundation/NSOperation.h>

@class NSURLSessionDataTask;

@interface com_vanna_KhmerKeyboard_Keyboard.HTTP : NSOperation {

	 onFinish;
	 task;
	 running;
	 done;
	 _cancelled;

}

@property (copy,nonatomic) id auth; 
@property (copy,nonatomic) id progress; 
@property (retain,nonatomic) NSURLSessionDataTask * task; 
@property (readonly,nonatomic) BOOL asynchronous; 
@property (readonly,nonatomic) BOOL executing; 
@property (readonly,nonatomic) BOOL finished; 
+(void)globalAuth:(/*^block*/id)arg1 ;
+(void)globalRequest:(/*^block*/id)arg1 ;
-(id)init:(id)arg1 session:(id)arg2 ;
-(BOOL)isAsynchronous;
-(void)cancel;
-(id)init;
-(void)setProgress:(id)arg1 ;
-(void)start;
-(NSURLSessionDataTask *)task;
-(id)progress;
-(BOOL)isFinished;
-(BOOL)isExecuting;
-(void)finish;
-(void)setTask:(NSURLSessionDataTask *)arg1 ;
-(void)setAuth:(id)arg1 ;
-(id)auth;
@end

