/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 4, 2016 at 9:15:10 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKGraphRequestPiggybackManager : NSObject
+(void)addRefreshPiggybackIfStale:(id)arg1 ;
+(void)addServerConfigurationPiggyback:(id)arg1 ;
+(void)addRefreshPiggyback:(id)arg1 permissionHandler:(/*^block*/id)arg2 ;
+(void)addPiggybackRequests:(id)arg1 ;
@end

