/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 4, 2016 at 9:15:10 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKTypeUtility : NSObject
+(id)dictionaryValue:(id)arg1 ;
+(unsigned long long)unsignedIntegerValue:(id)arg1 ;
+(id)stringValue:(id)arg1 ;
+(BOOL)boolValue:(id)arg1 ;
+(double)timeIntervalValue:(id)arg1 ;
+(id)arrayValue:(id)arg1 ;
+(id)URLValue:(id)arg1 ;
+(id)_objectValue:(id)arg1 ofClass:(Class)arg2 ;
+(id)objectValue:(id)arg1 ;
+(long long)integerValue:(id)arg1 ;
-(id)init;
@end

