/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 4, 2016 at 9:15:10 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@interface FBSDKError : NSObject
+(id)invalidArgumentErrorWithName:(id)arg1 value:(id)arg2 message:(id)arg3 ;
+(id)invalidArgumentErrorWithName:(id)arg1 value:(id)arg2 message:(id)arg3 underlyingError:(id)arg4 ;
+(id)unknownErrorWithMessage:(id)arg1 ;
+(BOOL)errorIsNetworkError:(id)arg1 ;
+(id)errorWithCode:(long long)arg1 message:(id)arg2 underlyingError:(id)arg3 ;
+(id)errorWithCode:(long long)arg1 userInfo:(id)arg2 message:(id)arg3 underlyingError:(id)arg4 ;
+(id)invalidCollectionErrorWithName:(id)arg1 collection:(id)arg2 item:(id)arg3 message:(id)arg4 underlyingError:(id)arg5 ;
+(id)requiredArgumentErrorWithName:(id)arg1 message:(id)arg2 underlyingError:(id)arg3 ;
+(id)invalidCollectionErrorWithName:(id)arg1 collection:(id)arg2 item:(id)arg3 message:(id)arg4 ;
+(id)requiredArgumentErrorWithName:(id)arg1 message:(id)arg2 ;
+(id)errorDomain;
+(id)errorWithCode:(long long)arg1 message:(id)arg2 ;
-(id)init;
@end

