/*
* This header is generated by classdump-dyld 1.0
* on Sunday, September 4, 2016 at 9:15:10 PM Indochina Time
* Operating System: Version 9.3.3 (Build 13G34)
* Image Source: /private/var/containers/Bundle/Application/EEBBBFB8-1B43-4927-9199-92E29DCE0E94/KhmerKeyboard.app/PlugIns/com.vanna.KhmerKeyboard.Keyboard.appex/com.vanna.KhmerKeyboard.Keyboard
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


@class NSString, NSData;

@interface FBSDKGraphRequestDataAttachment : NSObject {

	NSString* _contentType;
	NSData* _data;
	NSString* _filename;

}

@property (nonatomic,copy,readonly) NSString * contentType;              //@synthesize contentType=_contentType - In the implementation block
@property (nonatomic,readonly) NSData * data;                            //@synthesize data=_data - In the implementation block
@property (nonatomic,copy,readonly) NSString * filename;                 //@synthesize filename=_filename - In the implementation block
-(id)initWithData:(id)arg1 filename:(id)arg2 contentType:(id)arg3 ;
-(id)init;
-(NSData *)data;
-(NSString *)contentType;
-(NSString *)filename;
@end

